#!/bin/bash
# Nautilus script to check Talairach registration.

# INSTALL:
# mkdir -p ~/.gnome2/nautilus-scripts
# cp "script.sh" ~/.gnome2/nautilus-scripts/
# chmod +x ~/.gnome2/nautilus-scripts/"script.sh"

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 04/01/2013

FREESURFER_HOME=/usr/local/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do    
  SUBJECTS_DIR=$(dirname $i)
  #opts="--s $(basename $i) --fstal --surf"
  opts="--s $(basename $i) --fstal"

  # check
  #zenity --info --text="$opts"

  # execute
  xterm -e "tkregister2 ${opts}"
done


