#!/bin/bash
# mri_probedicom wrapper for Nautilus.

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 04/10/2014

source $(dirname $0)/env_vars

for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
    xterm -geometry 100x40 -bg black -fg green -e /bin/bash -c "mri_probedicom --i $i | less"
done



