#!/bin/bash
# freeview wrapper for Nautilus.

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 02/25/2013

fsaverage=1
source $(dirname $0)/FREESURFER_freeview
