#!/bin/bash
# freeview wrapper for Nautilus.

# INSTALL:
# mkdir -p ~/.gnome2/nautilus-scripts
# cp "script.sh" ~/.gnome2/nautilus-scripts/
# chmod +x ~/.gnome2/nautilus-scripts/"script.sh"

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 01/12/2013

source $(dirname $0)/env_vars

tmpfile=/tmp/$(basename $0)_$$

vollist_lh=""   ; vollist_rh=""
surflist_lh=""  ; surflist_rh=""
overlist_lh=""  ; overlist_rh=""
annotlist_lh="" ; annotlist_rh=""
labels_lh=""    ; labels_rh=""
lastfile=""
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
    
  niigz=$(echo $i | grep "\.nii.gz$" | wc -l)
  nii=$(echo $i | grep "\.nii$" | wc -l)
  mgh=$(echo $i | grep "\.mgh$" | wc -l)
  mgz=$(echo $i | grep "\.mgz$" | wc -l)
  
  label=$(echo $i | grep "\.label$" | wc -l)  
  patch=$(echo $i | grep "\.patch\." | wc -l)  
  annot=$(echo $i | grep "\.annot$" | wc -l)
  
  sig=$(echo $(basename $i) | grep "sig\.mgh$" | wc -l)
  F=$(echo $(basename $i) | grep "^F\.mgh$" | wc -l)
  gamma=$(echo $(basename $i) | grep "^gamma\.mgh$" | wc -l)
  gammavar=$(echo $(basename $i) | grep "^gammavar\.mgh$" | wc -l)
  cnr=$(echo $(basename $i) | grep "^cnr\.mgh$" | wc -l)
  
  if [ $mgz -eq 0 ] ; then
    mri_info $i > $tmpfile  
    type=$(cat $tmpfile | grep type: | head -n1 | cut -d : -f 2)  
    isscalar=$(cat $tmpfile | grep dimensions | cut -d : -f 2- | grep "x 1 x 1" | wc -l)
    rm $tmpfile
  else
    type=XXX
    isscalar=0
  fi
  
  # left or right hemisphere ?
  lh=0 ; rh=0
  lh="$(echo $(basename $i) | grep "\.lh\." | wc -l )"
  rh="$(echo $(basename $i) | grep "\.rh\." | wc -l )"
  if [ $lh -eq 0 ] ; then lh="$(echo $(basename $i) | grep "^lh\." | wc -l )" ; fi
  if [ $rh -eq 0 ] ; then rh="$(echo $(basename $i) | grep "^rh\." | wc -l )" ; fi
  _dir="$i"
  while [ $lh -eq 0 -a $rh -eq 0 ] ; do
    _dir=$(dirname $_dir) ; if [ "$_dir" = "$(dirname $_dir)" ] ; then break ; fi
    _dirname=$(basename $_dir)
    _hemi="$(basename $_dirname)"
    lh=$(echo $_hemi | grep "^lh\."  | wc -l)
    rh=$(echo $_hemi | grep "^rh\."  | wc -l)
    if [ $lh -eq 0 ] ; then lh=$(echo $_hemi | grep "\.lh\." | wc -l) ; fi
    if [ $rh -eq 0 ] ; then rh=$(echo $_hemi | grep "\.rh\." | wc -l) ; fi
    if [ $lh -eq 0 ] ; then lh=$(echo $_hemi | grep "\-lh\-" | wc -l) ; fi
    if [ $rh -eq 0 ] ; then rh=$(echo $_hemi | grep "\-rh\-" | wc -l) ; fi
    #zenity --info --text="$_dir"
  done
  
  # check
  #zenity --info --text="$rh $lh"
  
  if [ $sig -eq 1 -o $F -eq 1 ] ; then # file is a significance map...  
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      overlist_lh=$overlist_lh":overlay=$i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      overlist_rh=$overlist_rh":overlay=$i"
    fi
  elif [ $type = "MGH" -a $isscalar -eq 1 ] ; then # file is (probably) a scalar
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      overlist_lh=$overlist_lh":overlay=$i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      overlist_rh=$overlist_rh":overlay=$i"
    fi
  elif [ $niigz -eq 1 -o $nii -eq 1 -o $mgh -eq 1 -o $mgz -eq 1 ] ; then # file is a volume...    
    vollist_rh=$vollist_rh" -v $i"
  elif [ $annot -eq 1 ] ; then # file is an annotation...
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      annotlist_lh=$annotlist_lh":annot=$i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      annotlist_rh=$annotlist_rh":annot=$i"
    fi
  elif [ $label -eq 1 ] ; then # file is a surface label
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      labels_lh=$labels_lh":label=$i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      labels_rh=$labels_rh":label=$i"
    fi
  else
    if [ $type = "curv" ] ; then # file is an overlay...
      if [ $lh -eq 1 ] ; then # ...of the left hemi.
        overlist_lh=$overlist_lh":overlay=$i"
      elif [ $rh -eq 1 ] ; then # ...of the right hemi.
        overlist_rh=$overlist_rh":overlay=$i"
      fi
    elif [ x$type = "x" ] ; then # file is a surface...
      if [ $lh -eq 1 ] ; then # ...of the left hemi.
        surflist_lh=$surflist_lh" -f $i"
      elif [ $rh -eq 1 ] ; then # ...of the right hemi.
        surflist_rh=$surflist_rh" -f $i"
      fi
    fi    
  fi
done # end for loop

# add fsaverage surface and annotation if applicable
if [ $fsaverage -eq 1 ] ; then
  if [ $lh -eq 1 ] ; then 
    surflist_lh=$surflist_lh" -f $SUBJECTS_DIR/fsaverage/surf/lh.inflated"
    annotlist_lh=$annotlist_lh":annot=$SUBJECTS_DIR/fsaverage/label/lh.aparc.a2009s.annot"
  elif [ $rh -eq 1 ] ; then
    annotlist_rh=$annotlist_rh":annot=$SUBJECTS_DIR/fsaverage/label/rh.aparc.a2009s.annot"
    surflist_rh=$surflist_rh" -f $SUBJECTS_DIR/fsaverage/surf/rh.inflated"
  fi
fi

# remove spaces before ':' in freeview arguments
opts=$(echo "${vollist_lh} ${vollist_rh} ${surflist_lh}${annotlist_lh}${overlist_lh}${labels_lh} ${surflist_rh}${annotlist_rh}${overlist_rh}${labels_rh}" | sed "s| :|:|g") 

# check
#zenity --info --text="$opts"

# execute
freeview ${opts}

