#!/bin/bash
# freeview wrapper for Nautilus.

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 12/01/2012

FREESURFER_HOME=/usr/local/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

vollist_lh=""   ; vollist_rh=""
surflist_lh=""  ; surflist_rh=""
overlist_lh=""  ; overlist_rh=""
annotlist_lh="" ; annotlist_rh=""
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  niigz=$(echo $i | grep .nii.gz$ | wc -l)
  nii=$(echo $i | grep .nii$ | wc -l)
  mgh=$(echo $i | grep .mgh$ | wc -l)
  mgz=$(echo $i | grep .mgz$ | wc -l)
  
  annot=$(echo $i | grep .annot$ | wc -l)
  
  sig=$(echo $(basename $i) | grep ^sig.mgh$ | wc -l)
  F=$(echo $(basename $i) | grep ^F.mgh$ | wc -l)
  gamma=$(echo $(basename $i) | grep ^gamma.mgh$ | wc -l)
  gammavar=$(echo $(basename $i) | grep ^gammavar.mgh$ | wc -l)
  cnr=$(echo $(basename $i) | grep ^cnr.mgh$ | wc -l)
  
  # left or right hemisphere ?
  lh=0 ; rh=0
  if [ "$(echo $(basename $i) | cut -d . -f 1)" = "lh" ] ; then
    lh=1
  else
    rh=1
  fi
  
  # check
  #zenity --info --text="$rh $lh"
  
  if [ $sig -eq 1 -o $F -eq 1 -o $gamma -eq 1 -o $gammavar -eq 1 -o $cnr -eq 1 ] ; then # file is a statistical map...  
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      overlist_lh=$overlist_lh":overlay=$i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      overlist_rh=$overlist_rh":overlay=$i"
    fi
  elif [ $niigz -eq 1 -o $nii -eq 1 -o $mgh -eq 1 -o $mgz -eq 1 ] ; then # file is a volume...    
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      vollist_lh=$vollist_lh" -v $i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      vollist_rh=$vollist_rh" -v $i"
    fi
  elif [ $annot -eq 1 ] ; then # file is an annotation...
    if [ $lh -eq 1 ] ; then # ...of the left hemi.
      annotlist_lh=$annotlist_lh":annot=$i"
    elif [ $rh -eq 1 ] ; then # ...of the right hemi.
      annotlist_rh=$annotlist_rh":annot=$i"
    fi
  else
    type=$(mri_info $i | grep type: | head -n1 | cut -d : -f 2)
    if [ $type = "curv" ] ; then # file is an overlay...
      if [ $lh -eq 1 ] ; then # ...of the left hemi.
        overlist_lh=$overlist_lh":overlay=$i"
      elif [ $rh -eq 1 ] ; then # ...of the right hemi.
        overlist_rh=$overlist_rh":overlay=$i"
      fi
    elif [ x$type = "x" ] ; then # file is a surface...
      if [ $lh -eq 1 ] ; then # ...of the left hemi.
        surflist_lh=$surflist_lh" -f $i"
      elif [ $rh -eq 1 ] ; then # ...of the right hemi.
        surflist_rh=$surflist_rh" -f $i"
      fi
    fi    
  fi
done # end for loop

# remove spaces before ':' in freeview arguments
opts=$(echo "${vollist_lh} ${vollist_rh} ${surflist_lh}${annotlist_lh}${overlist_lh} ${surflist_rh}${annotlist_rh}${overlist_rh}" | sed "s| :|:|g") 

# check
zenity --info --text="$opts"

# execute
freeview ${opts}

