#!/bin/bash
# freeview wrapper for Nautilus.

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 11/19/2012

FREESURFER_HOME=/usr/local/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

vollist="" ; surflist="" ; overlist=""
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  niigz=$(echo $i | grep .nii.gz$ | wc -l)
  nii=$(echo $i | grep .nii$ | wc -l)
  mgh=$(echo $i | grep .mgh$ | wc -l)
  mgz=$(echo $i | grep .mgz$ | wc -l)
  
  if [ $niigz -eq 1 -o $nii -eq 1 -o $mgh -eq 1 -o $mgz -eq 1 ] ; then # file is a volume
    vollist=$vollist" -v $i" 
  else
    type=$(mri_info $i | grep type: | head -n1 | cut -d : -f 2)
    if [ $type = "curv" ] ; then # file is an overlay
      overlist=$overlist":overlay=$i"
    elif [ x$type = "x" ] ; then # file is a surface
      surflist=$surflist" -f $i"
    #else
      #vollist=$vollist" -v $i"
    fi
  fi
done

#zenity --info --text="$vollist ${surflist}${overlist}"
freeview $vollist $surflist"$overlist"

