#!/bin/bash

source $(dirname $0)/env_vars

# create unique dir. for temporary files
export tmpdir=$(mktemp -d -t $(basename $0)_XXXXXXXXXX)

# define exit trap
trap "rm -f $tmpdir/* ; rmdir $tmpdir ; exit" EXIT

# define vars
opts=$(zenity --entry --text="Enter fslmaths option:" --entry-text="")
_opts="$(echo "$opts" | sed 's| ||g')"
#_opts="$(echo "$opts" | sed 's|-||g')"

# save command to list
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  out="$(dirname $i)/$(basename $(remove_ext $i))_${_opts}"
  echo "fslmaths $i $opts $out" >> $tmpdir/cmd
done

# execute
xterm -e /bin/bash -c "\
cat $tmpdir/cmd ; \
. $tmpdir/cmd ; \
echo ; \
read -p Press\ key..."
