#!/bin/bash
# Fslview wrapper for Nautilus. Also converts and displays Freesurfer volumes. No blanks allowed.

# INSTALL:
# mkdir -p ~/.gnome2/nautilus-scripts
# cp "script.sh" ~/.gnome2/nautilus-scripts/
# chmod +x ~/.gnome2/nautilus-scripts/"script.sh"

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 11/18/2012

source $(dirname $0)/env_vars

# create unique dir. for temporary files
export tmpdir=$(mktemp -d -t $(basename $0)_XXXXXXXXXX)

# define exit trap
trap "rm -f $tmpdir/* ; rmdir $tmpdir ; exit" EXIT

n=0 ; files="" ; links2del=""
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  bn=$(basename $i) ; ext=`echo ${bn##*.}` ;  bn0=${bn%.*}
  if [ "$ext" = "mgz" -o "$ext" = "mgh" ] ; then
    #zenity --info --text="   mri_convert $i $tmpdir/$bn0.nii.gz $FSLDIR"
    mri_convert $i $tmpdir/${bn0}.nii.gz
    ln -s $tmpdir/${bn0}.nii.gz $(dirname $i)/${bn}_$$.nii.gz # create symlink in parent folder (so that "open" in fslview shows parent folder instead of temporary folder)
    if [ -f $(dirname $i)/${bn}_$$.nii.gz ] ; then
      files=$files" "$(dirname $i)/${bn}_$$.nii.gz
      links2del=$links2del" "$(dirname $i)/${bn}_$$.nii.gz
    else # symlink could not be created for some reason (e.g., no write access)
      files=$files" "$tmpdir/${bn0}.nii.gz
    fi
    n=$[$n+1]
  else
    files=$files" "$i
  fi
done

#for i in $files ; do
  #sizex=$($FSLDIR/bin/fslinfo $i | grep pixdim1 | cut -d " " -f 2-)
  #sizey=$($FSLDIR/bin/fslinfo $i | grep pixdim2 | cut -d " " -f 2-)
  #sizez=$($FSLDIR/bin/fslinfo $i | grep pixdim3 | cut -d " " -f 2-)
  #zenity --info --text="$i $sizex $sizey $sizez"
#done

# execute
fslview $files

# cleanup
rm -f $links2del
