#!/bin/bash
# Fslview wrapper for Nautilus. Also converts and displays Freesurfer volumes.

# INSTALL:
# mkdir -p ~/.gnome2/nautilus-scripts
# cp "script.sh" ~/.gnome2/nautilus-scripts/
# chmod +x ~/.gnome2/nautilus-scripts/"script.sh"

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 11/18/2012

FREESURFER_HOME=/usr/local/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
#FSLDIR=/usr/share/fsl/4.1
#zenity --info --text="$FSLDIR"

if [ -d /tmp ] ; then
  wdir=/tmp/.fslviewscript$$
else
  wdir=`pwd`/.fslviewscript$$
fi
mkdir -p $wdir

# define exit trap
trap "echo -e \"\ncleanup: erasing '$wdir'\" ; rm -f $wdir/* ; rmdir $wdir ; exit" EXIT

n=0 ; files="" ; links2del=""
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  bn=$(basename $i) ; ext=`echo ${bn##*.}` ;  bn0=${bn%.*}
  if [ "$ext" = "mgz" -o "$ext" = "mgh" ] ; then
    #zenity --info --text="   mri_convert $i $wdir/$bn0.nii.gz $FSLDIR"
    mri_convert $i $wdir/${bn0}.nii.gz
    ln -s $wdir/${bn0}.nii.gz $(dirname $i)/${bn0}_$$.nii.gz
    files=$files" "$(dirname $i)/${bn0}_$$.nii.gz
    links2del=$links2del" "$(dirname $i)/${bn0}_$$.nii.gz
    n=$[$n+1]
  else
    files=$files" "$i
  fi
done

#for i in $files ; do
  #sizex=$($FSLDIR/bin/fslinfo $i | grep pixdim1 | cut -d " " -f 2-)
  #sizey=$($FSLDIR/bin/fslinfo $i | grep pixdim2 | cut -d " " -f 2-)
  #sizez=$($FSLDIR/bin/fslinfo $i | grep pixdim3 | cut -d " " -f 2-)
  #zenity --info --text="$i $sizex $sizey $sizez"
#done

# execute
fslview $files

# cleanup
rm -f $links2del
