#!/bin/bash

source $(dirname $0)/env_vars

## create unique dir. for temporary files
#export tmpdir=$(mktemp -d -t $(basename $0)_XXXXXXXXXX)

## define exit trap
#trap "rm -f $tmpdir/* ; rmdir $tmpdir ; exit" EXIT

files=""
for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  files=$files" "$i
done

out=$(zenity --entry --text="Enter output filename:" --entry-text="merged")

cmd1="mkdir -p $(dirname $out)"
cmd2="fslmerge -t $out $files"

# execute
xterm -e /bin/bash -c "n=0 ; for i in $files ; do echo \$i ; n=\$[\$n+1] ; done ; echo n=\$n ; \
echo ; \
echo $cmd1 ; \
$cmd1 ; \
echo $cmd2 ; \
$cmd2 ; \
echo ; \
read -p Press\ key..."
