#!/bin/bash
# fslhd wrapper for nautilus

# Written by Andreas Heckel
# University of Heidelberg
# heckelandreas@googlemail.com
# https://github.com/ahheckel
# 09/04/2014

source $(dirname $0)/env_vars

for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  xterm -geometry 100x80 -bg black -fg green -e /bin/bash -c "fslhd $i ; read -p Press\ key..."
done
