#!/bin/bash

source $(dirname $0)/env_vars

for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  xterm -geometry 240x80 -bg black -fg green -sb -sl 65536 -e /bin/bash -c "echo start... ; $scriptdir/greperror.sh $i ; echo ; read -p Press\ key..." 
done
