#!/bin/bash

for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ; do
  xterm -geometry 240x80  -bg black -fg green -sb -sl 65536 -e "echo start... ; /FSL-scripts/rsc/scripts/greperror.sh $i ; echo ; read -p \"Press key...\"" 
done
