#!/bin/bash

########################################################################
# set paths ############################################################
########################################################################

studydir=`pwd` # absolute path
srcdir=$studydir/subj
subjdir=$studydir/subj
grpdir=$studydir/grp
glmdir=$grpdir/glm
logdir=$studydir/logs 

tbssdir=$grpdir/tbss        ; glmdir_tbss=$glmdir/tbss
vbmdir=$grpdir/vbm          ; glmdir_vbm=$glmdir/vbm
alffdir=$grpdir/alff        ; glmdir_alff=$glmdir/alff
gicadir=$grpdir/melodic
dregdir=$grpdir/dualreg     ; glmdir_dr=$glmdir/dualreg
FSstatsdir=$grpdir/FS_stats ; glmdir_fs=$glmdir/FS_stats
fslnetsdir=$grpdir/fslnets  ; glmdir_fslnets=$glmdir/fslnets

FS_subjdir=$subjdir/FS_subj
FS_sessdir=$subjdir/FS_sess
export SUBJECTS_DIR=$FS_subjdir

########################################################################
# set file patterns ####################################################
########################################################################

# set file patterns
pttrn_diffs="*_ep2ddiff_pat3_esp0_75ms_*-.nii" ; pttrn_bvals=`remove_ext $pttrn_diffs`_bvals ; pttrn_bvecs=`remove_ext $pttrn_diffs`_bvecs
pttrn_fmaps="*_gre_field_mapping.nii "
pttrn_strucs="*T1_MPRAGE_tra_256_1_0mm_nopat.nii"
pttrn_bolds="*resting_TE30_pat3_esp0_7_Filter.nii"

# set file patterns for TOPUP
pttrn_diffsplus="*_ep2ddiff_pat3_esp0_75ms_*+.nii"  ; pttrn_bvalsplus=`remove_ext $pttrn_diffsplus`_bvals   ; pttrn_bvecsplus=`remove_ext $pttrn_diffsplus`_bvecs 
pttrn_diffsminus="*_ep2ddiff_pat3_esp0_75ms_*-.nii" ; pttrn_bvalsminus=`remove_ext $pttrn_diffsminus`_bvals ; pttrn_bvecsminus=`remove_ext $pttrn_diffsminus`_bvecs

########################################################################
# enable 1st level processing streams ##################################
########################################################################

SCRATCH=0                  # execute scratchpad and exit

FIELDMAP_STG1=0            # FIELDMAP prepare
FIELDMAP_STG2=0            # FIELDMAP create

TOPUP_STG1=0               # TOPUP prepare
TOPUP_STG2=0               # TOPUP low-B images: create index and extract
TOPUP_STG3=0               # TOPUP merge B0 images
TOPUP_STG4=0               # TOPUP execute topup
TOPUP_STG5=0               # TOPUP apply warp
TOPUP_STG6=0               # TOPUP estimate tensor model

FDT_STG1=0                 # FDT merging
FDT_STG2=0                 # FDT eddy-correct & extract B0 reference image
FDT_STG3=0                 # FDT unwarp the DWIs
FDT_STG4=0                 # FDT estimate tensor model

BPX_STG1=0                 # BedpostX - execute

RECON_STG1=0               # RECON-ALL prepare (copy and convert T1 nifti)
RECON_STG2=0               # RECON-ALL execute cross-sectional stream
RECON_STG3=0               # RECON-ALL execute longitudinal stream's template creation
RECON_STG4=0               # RECON-ALL execute longitudinal processing for each timepoint
RECON_STG5=0               # RECON-ALL register FS's longitudinal template (if applicable) or brain.mgz to FSL's MNI152 template using fnirt

VBM_STG1=0                 # VBM prepare T1
VBM_STG2=0                 # VBM initial skull strip
VBM_STG3=0                 # VBM apply standard space mask (SSM)
VBM_STG4=0                 # VBM final skull strip - bet
VBM_STG5=0                 # VBM final skull strip - watershed

TRACULA_STG1=0             # TRACULA prepare
TRACULA_STG2=0             # TRACULA execute -prep
TRACULA_STG3=0             # TRACULA execute -bedp
TRACULA_STG4=0             # TRACULA execute -path

BOLD_STG1=0                # BOLD prepare FEAT configuration file for motion correction and unwarping, etc.
BOLD_STG2=0                # BOLD execute FEAT configuration file
BOLD_STG3=0                # BOLD denoising (needs Freesurfer recons)
BOLD_STG4=0                # BOLD write MNI-registered volumes
BOLD_STG5=0                # BOLD denoise MNI-registered volumes

ALFF_STG1=0                # ALFF preproc
ALFF_STG2=0                # ALFF denoise
ALFF_STG3=0                # ALFF MNI registration

########################################################################
# enable second level analyses #########################################
########################################################################

TBSS_STG1=0                # TBSS prepare 
TBSS_STG2=0                # TBSS threshold skeleton 
TBSS_STG3=0                # TBSS permutation testing
TBSS_STG4=0                # TBSSX prepare - needs BedpostX (!)
TBSS_STG5=0                # TBSSX permutation testing

FS_STATS_STG1=0            # FS_STATS resample thickness measure to average surface
FS_STATS_STG2=0            # FS_STATS smoothing
FS_STATS_STG3=0            # FS_STATS GLM
FS_STATS_STG4=0            # FS_STATS GLM permutation testing

VBM_2NDLEV_STG1=0          # VBM prepare 
VBM_2NDLEV_STG2=0          # VBM smooth
VBM_2NDLEV_STG3=0          # VBM permutation testing

MELODIC_2NDLEV_STG1=0      # MELODIC create *.fsf file 
MELODIC_2NDLEV_STG2=0      # MELODIC create sym-links to t1-structurals

MELODIC_CMD_STG1=0         # MELODIC use melodic-command line tool (optional)

DUALREG_STG1=0             # DUALREG prepare for randomie
DUALREG_STG2=0             # DUALREG randomise

ALFF_2NDLEV_STG1=0         # ALFF prepare
ALFF_2NDLEV_STG2=0         # ALFF randomise

FSLNETS_STG1=0             # prepare and execute FSLNETS in MATLAB (requires dualreg-input)

########################################################################
# configuration ########################################################
########################################################################

# SGE CLUSTER
#SGE_ROOT=""                    # set SGE_ROOT to empty, if no cluster, otherwise comment this line out

# FIRST LEVEL
# overwrite pre-existing subject /session file (to disable set any to "")
FIRSTLEV_SUBJECTS="01 02 03 04 flip04 05 flip05 06 flip06 07 flip07 08 09 flip09 10" 
FIRSTLEV_SESSIONS_FUNC="a b c d e" # enter "." for single session designs
FIRSTLEV_SESSIONS_STRUC="a c e"    # enter "." for single session designs          

# SECOND LEVEL
SECONDLEV_SUBJECTS="01 02 03 flip04 flip05 flip06 flip07 08 flip09 10" 
SECONDLEV_SESSIONS_FUNC="a b c d e" # enter "." for single session designs            
SECONDLEV_SESSIONS_STRUC="a c e"    # enter "." for single session designs

# ACQUISITION PARAMETERS
TROT_topup=0.02975              # TOPUP DWI total readout time in seconds (EES_diff * (PhaseEncodingSteps - 1), i.e. 0.25 * 119 / 1000)
TR_diff=11                      # DWI TR of the DWIs (s)
EES_diff=0.25                   # DWI Effective Echo Spacing of the DWIs (ms)
TE_diff=88                      # DWI TE of the DWIs (ms)
#-----------------------------------------------------------------------
TR_bold=3.330                   # BOLD TR (s)
EES_bold=0.23333                # BOLD Effective Echo Spacing (ms)
TE_bold=30                      # BOLD TE (ms)

#-----------------------------------------------------------------------
# first level analyses -------------------------------------------------
#-----------------------------------------------------------------------

# FIELDMAP
deltaTEphase=0.00246       # in seconds
PI=3.1415926532            # =$(echo "scale=10; 4*a(1)" | bc -l) # define pi

# TOPUP
TOPUP_USE_NATIVE=1         # apply TOPUP-warps to native DWI runs
TOPUP_USE_EC=1             # apply TOPUP-warps to eddy-corrected DWI runs (i.e. runs that have been eddy-corrected to the first B0 volume per run)
TOPUP_EC_DOF=12            # degrees of freedom used by eddy-correction
TOPUP_EC_COST=mutualinfo   # cost-function used by eddy-correction (default: corratio)
TOPUP_USE_EDDY=0           # use EDDY (FSL 5)

# FDT - unwarp
FDT_EC_TEST=0                  # don't apply eddy-correction
FDT_EC_DOF=12                  # degrees of freedom used by eddy-correction
FDT_EC_COST=mutualinfo         # cost-function used by eddy-correction (default: corratio)
FDT_UNWARP=1                   # do unwarp ?
FDT_FMAP="fm/fmap_rads_masked" # rel. path to fieldmap in rads/sec (default: "fm/fmap_rads_masked")
FDT_MAGN="fm/magn_brain"       # rel. path to magnitude (default: "fm/magn_brain")
FDT_SIGNLOSS_THRES=100         # signal loss threshold (%)
  
# BPX
BPX_OUTDIR_PREFIX="bpx"
BPX_OPTIONS="-n 2 -w 1 -b 1000 -model 2"  # default: "-n 2 -w 1 -b 1000" ; CAVE: -model switch not supported in FSL 4.
BPX_USE_NOEC=0
BPX_USE_EC_NOROT=0
BPX_USE_EC_BVECROT=0
BPX_USE_UNWARPED_NOROT=0
BPX_USE_UNWARPED_BVECROT=0
BPX_USE_TOPUP_NOEC_BVECROT=0
BPX_USE_TOPUP_EC_BVECROT=1
BPX_USE_TOPUP_EDDY_NOROT=0

# RECON-ALL
RECON_USE_CUDA=0           # use CUDA for recon-all, if available
RECON_USE_MRITOTAL=0       # may improve talairach registration

# VBM_PREPROC
VBM_FSLV5=0                # perform fsl_anat script
VBM_NU_CORRECT_T1=0        # perform non-uniformity correction prior to t1 skull-stripping - useful for mri_watershed (default: 0)
VBM_SSM_ERODE_STEPS=3
                           # mutually exclusive:
VBM_USE_WATERSHED_INIT=0   # use watershed brain to initialize standard space masking
VBM_USE_BETTED_INIT=1      # use betted brain as init. for standard space masking (default: 1)

# TRACULA
# mutually exclusive:
TRACULA_USE_NATIVE=0             # use unprocessed merged DWI files (TRACULA does eddy-correction and bvec. rotation)
TRACULA_USE_UNWARPED_BVECROT=0   # use unwarped and eddy-corrected merged DWI files and corrected b-vectors
TRACULA_USE_TOPUP_NOEC_BVECROT=0 # use TOPUP corrected merged DWI files with corrected b-vectors
TRACULA_USE_TOPUP_EC_BVECROT=1   # use TOPUP corrected & eddy-corrected merged DWI files with corrected b-vectors

# BOLD - preproc
BOLD_FEATDIR_PREFIX="preprocBOLD"                             # prefix for .feat output directory
BOLD_BET_EXFUNC=0                                             # bet example func (middle of the 4D) (default 0)
BOLD_FEAT_NO_BROWSER=1                                        # don't open browser window
#---------------------
BOLD_MC=1                                                     # enable motion correction
BOLD_UNWARP=1                                                 # enable unwarping (default 1)
BOLD_FMAP="fm/fmap_rads_masked"                               # rel. path to fieldmap in rads/sec (e.g. topup/fm/fmap_rads ; default: fm/fmap_rads_masked) - CAVE: topup fieldmaps: unwarp direction may differ from fieldmap-based unwarping !
BOLD_MAGN="fm/magn_brain"                                     # rel. path to magnitude (e.g. topup/fm/uw_lowb_mean_brain ; default: fm/magn_brain)
BOLD_SIGNLOSS_THRES=10 	                                      # signal loss threshold (%) (default: 10)
BOLD_SLICETIMING_VALUES="0"                                   # enter correction method (see .fsf file); "0" to switch off slice timing correction
BOLD_BET=1                                                    # enable betting (default 1)
BOLD_SMOOTHING_KRNLS="0 4"                                    # FWHM (mm) ; enter "0" to swith off smoothing (note: the '.' decimal separator will be removed in the directory name for feat-compatibility purposes) 
BOLD_HPF_CUTOFFS="100"                                        # enter "Inf" or "" to switch off high-pass filter
BOLD_REGISTER_TO_STRUC_DOF=6                                  # degrees of freedom when registering bold -> T1
BOLD_PTTRN_HIGHRES_BRAIN="*_FS_brain.nii.gz"                  # pattern of t1 skull-stripped image
BOLD_PTTRN_HIGHRES_STRUC="*_FS_struc.nii.gz"                  # pattern of t1 non-skull-stripped image
#---------------------
BOLD_DENOISE_MASKS_NAT="EF_CSF EF_WM"                         # masks used for denoising [EF_CSF.nii.gz EF_WB.nii.gz EF_WM.nii.gz EF_GM.nii.gz ; "none" to switch off] located in feat-dir (need FS-recons for creation) -> see FS_create_masks.sh
BOLD_DENOISE_USE_MOVPARS_NAT="1"                              # 0: none - 1: orig - 2: squared - 3: abs - 4: 1st deriv. with leading zero - 5: 1st deriv. with trailing zero ; CAVE: cannot take more than 4 motion related modes (4*6=24 regressors -> more lead to fsl_regfilt error (at least at 32 bit)) (!)
BOLD_DENOISE_SMOOTHING_KRNLS="4"                              # smooth denoised data (NOTE: denoising of native data requires feat-processed data without smoothing applied)
#---------------------
BOLD_REGISTER_TO_MNI=1                                        # enable MNI registration
BOLD_USE_FS_LONGT_TEMPLATE=2                                  # using FS's mid-long template as unbiased registration basis for multisession designs (0: off / 1: bold->t1->long.template / 2: bold->long.template)
BOLD_MNI_RESAMPLE_FUNCDATAS="filtered_func_data      filtered_func_data_denoised_s2      filtered_func_data_denoised_s4"              # cycle through 4Ds that are to be resampled in MNI space
BOLD_MNI_RESAMPLE_RESOLUTIONS="2 4"                           # resolution of the mni-registered data (0: disable) - note: the '.' decimal separator will be removed in the directory name for feat-compatibility purposes; note also: 1 mm may give "out of mem" error
BOLD_MNI_RESAMPLE_INTERP="trilinear"                          # interpolation method for resampling MNI registered BOLDs (sinc, spline, trilinear)
#---------------------
BOLD_DENOISE_MASKS_MNI="MNI_CSF MNI_WM"                       # masks used for denoising in MNI space (filtered_func_data with 2mm resolution must be present to estimate nuisance matrix)
BOLD_DENOISE_USE_MOVPARS_MNI="1"                              # see above

# ALFF
ALFF_DENOISE_MASKS_NAT="none"                                   # enter "none" to switch off (default: none), o.w. e.g. "EF_CSF EF_WB EF_WM"
ALFF_DENOISE_USE_MOVPARS_NAT="0"                                # enter "0" to switch off (default: 0)
ALFF_SMOOTHING_KERNEL=6                                         # enter FWHM in mm (default: 6)
ALFF_HPF_CUTOFF=""                                              # enter "none", "" or "Inf" to use AFNI's detrending tool (default "")
ALFF_BANDPASS="0.01,0.1"                                        # enter bandpass (default: "0.01,0.1")
ALFF_FSLV5=0                                                    # in FSL 5 naming of unwarp shiftmap and its location is different
ALFF_FEATDIR="bold/preprocBOLD_uw??_st0_s0_hpf100.feat"         # featdir where transforms are located: e.g. "bold/preprocBOLD_uw??_st0_s0_hpf100.feat", where ?? is a placeholder for the unwarp direction (sed)
ALFF_APPLY_MC=1                                                 # apply motion correction ?
ALFF_APPLY_UNWARP=1                                             # apply shiftmap ?
ALFF_MNI_AFFINE="reg_longt/example_func2longt_brain.mat"        # e.g. "reg_longt/example_func2longt_brain.mat" or "reg/example_func2highres.mat"
ALFF_MNI_WARP="reg_longt/longt_head2longt_standard_warp.nii.gz" # e.g. "reg_longt/longt_head2longt_standard_warp.nii.gz" or "reg/highres2standard_warp.nii.gz"
ALFF_RESAMPLING_RESOLUTIONS="2"                                 # enter resolution (default: "2")

#-----------------------------------------------------------------------
# second level analyses ------------------------------------------------
#-----------------------------------------------------------------------

# TBSS     
TBSS_INCLUDED_SUBJECTS=$SECONDLEV_SUBJECTS        # subjects to be included in the TBSS analysis
TBSS_INCLUDED_SESSIONS=$SECONDLEV_SESSIONS_STRUC  # sessions to be included in the TBSS analysis
TBSS_USE_BPX_FROM_TRACULA=0                       # use BedpostX files from TRACULA, otherwise use from BPX stream
TBSS_BPX_INDIR_PREFIX="bpx"                       # prefix of BedpostX input directory (for TBSSX, if files from TRACULA stream are not used)
TBSS_OUTDIR_PREFIX="tbss"                         # prefix of output directory
TBSS_USE_B0_4_FS_LONGT=""                         # use FREESURFER'S longitudinal template to register the b0 to (default "", e.g. "topup/fm/uw_lowb_mean_brain" or "fdt/uw_nodif")
TBSS_THRES="0.2 0.3 0.4"                          # cycle through some skeleton-threshold values
TBSS_Z_TRANSFORM=1                                # z-transform FA skeletons
TBSS_RANDOMISE_OPTS="--T2 -V -x -n 5000"          # randomise options (e.g.: "--T2 -V -x -n 5000")
TBSS_DELETE_PREV_RUNS=1                           # delete previously created TBSS directories and files; if set, no questions will be asked
# NOTE: if you use BedpostX files from TRACULA for TBSSX, then you should chose the (*single*) appropriate switch from below to ensure proper naming
TBSS_USE_NOEC=0                                   # use FA maps from non eddy-corrected DWIs
TBSS_USE_EC_NOROT=0                               # use FA maps from eddy-corrected DWIs w/o b-vector compensation
TBSS_USE_EC_BVECROT=0                             # use FA maps from eddy-corrected DWIs with b-vector compensation applied
TBSS_USE_UNWARPED_NOROT=0                         # use FA maps from eddy-corrected & unwarped DWIs w/o b-vector compensation
TBSS_USE_UNWARPED_BVECROT=0                       # use FA maps from eddy-corrected & unwarped DWIs with b-vector compensation applied
TBSS_USE_TOPUP_NOEC_BVECROT=0                     # use FA maps from TOPUP-corrected DWIs (w/o eddy-correction) with b-vector compensation applied
TBSS_USE_TOPUP_EC_BVECROT=1                       # use FA maps from TOPUP-corrected & eddy-corrected DWIs with b-vector compensation applied

# FS_STATS
FS_STATS_OUTDIR_PREFIX="fsstats"                  # outdir prefix; output directory is ${FS_STATS_OUTDIR_PREFIX}_${FS_STATS_GROUPSPACE}
FS_STATS_GROUPSPACE="fsaverage"                   # target subject for resampling data
FS_STATS_MEASURES="thickness"                     # list of dependent variables of FREESURFER analysis (e.g., "thickness")
FS_STATS_SMOOTHING_KRNLS="5 10 15 20"             # smoothing kernels (e.g., "5 10 15")
FS_STATS_NPERM=5000                               # number of permutations (null distribution)

# VBM
VBM_INCLUDED_SUBJECTS=$SECONDLEV_SUBJECTS         # subjects to be included in the VBM analysis
VBM_INCLUDED_SESSIONS=$SECONDLEV_SESSIONS_STRUC   # subjects to be included in the VBM analysis
VBM_OUTDIRNAME="vbm_FS"                           # name of output directory
VBM_USE_FS_LONGT=0                                # use FREESURFER'S longitudinal template (default 0)
VBM_PTTRN_BRAIN="*_FS_brain.nii.gz"               # search pattern for brain-extracted structurals
VBM_PTTRN_STRUC="*_FS_struc.nii.gz"               # search pattern for original structurals (w/o skull-strip)
VBM_SMOOTHING_KRNL="2 3 4"                        # cycle through some smoothing kernels
VBM_Z_TRANSFORM=1                                 # z-transform grey matter 4D
VBM_RANDOMISE_OPTS="-T -V -x -n 5000"      	      # randomise options (e.g.: "-T -V -x -n 5000")
VBM_DELETE_PREV_RUNS=1                            # delete previously created 2ndLevel VBM directories and files; if set, no questions will be asked

#ALFF
ALFF_INCLUDED_SUBJECTS=$SECONDLEV_SUBJECTS        # subjects to be included in the VBM analysis
ALFF_INCLUDED_SESSIONS=$SECONDLEV_SESSIONS_FUNC   # subjects to be included in the VBM analysis
ALFF_OUTDIRNAME="alff_01"                         # name of output directory
ALFF_RESOLUTIONS="2"                              # cycle through var. resolutions
ALFF_RANDOMISE_OPTS="-T -V -x -n 5000"      	    # randomise options (e.g.: "-T -V -x -n 5000")
ALFF_DELETE_PREV_RUNS=1                           # delete previously created 2ndLevel VBM directories and files; if set, no questions will be asked

# MELODIC GUI
MELODIC_INCLUDED_SUBJECTS=$SECONDLEV_SUBJECTS                  # subjects to be included in the ICA analysis
MELODIC_INCLUDED_SESSIONS=$SECONDLEV_SESSIONS_FUNC             # sessions to be included in the ICA analysis
MELODIC_INPUT_FILE="preprocBOLD_uw_st0_s0_hpf100_filtered_func_data_denoised_s2_longt_mni2.nii.gz" # filename of input file (in 'bold' subdirectory)
MELODIC_OUTDIRNAME="MELODIC-GUI01"                             # output directory (ommit '.gica' suffix)
MELODIC_PTTRN_HIGHRES_BRAIN="*_FS_brain.nii.gz"  # pattern of t1 skull-stripped image
MELODIC_PTTRN_HIGHRES_STRUC="*_FS_struc.nii.gz"                # pattern of t1 non skull-stripped image
MELODIC_BET=0                                                  # enable betting
MELODIC_SMOOTH=4.0                                             # smoothing kernel width in mm
MELODIC_REGSTD_RESOLUTION=4.0                                  # resampling resolution of normalised volumes volumes
MELODIC_HIGHPASS_CUTOFF=100                                    # high-pass filter cutoff value

# MELODIC_CMD (optional)
MELODIC_CMD_INCLUDED_SUBJECTS=$SECONDLEV_SUBJECTS               # subjects to be included in the ICA analysis
MELODIC_CMD_INCLUDED_SESSIONS=$SECONDLEV_SESSIONS_FUNC          # sessions to be included in the ICA analysis
MELODIC_CMD_INPUT_FILES="preprocBOLD_uw_st0_s0_hpf100_filtered_func_data_denoised_s4_longt_mni2    preprocBOLD_uw_st0_s0_hpf100_filtered_func_data_denoised_s4_longt_mni4"   # preprocBOLD_mni_uw_mc_bold_hpf100_s4_stc0_res4.nii.gz preprocBOLD_mni_uw_mc_bold_hpf100_s2_stc0_res2.nii.gz"  # filename of input file (in 'bold' subdirectory)
MELODIC_CMD_OUTDIR_PREFIX="MELODIC-CMD01"                       # output directory pre-fix (dir-name is composed as: ${MELODIC_OUTDIR_PREFIX}_${MELODIC_INPUT_FILE}.gica)
MELODIC_CMD_BET=0                                               # enable betting
MELODIC_CMD_DELETE_PREV_RUNS=1                                  # delete previously created melodic directories and files; if set, no questions will be asked

# DUALREG
DUALREG_INCLUDED_SUBJECTS=$SECONDLEV_SUBJECTS               # subjects that should be used with dualreg
DUALREG_INCLUDED_SESSIONS=$SECONDLEV_SESSIONS_FUNC          # sessions that should be used with dualreg
DUALREG_INPUT_ICA_DIRNAMES="MELODIC-CMD01_preprocBOLD_uw_st0_s0_hpf100_filtered_func_data_denoised_s4_longt_mni2    MELODIC-CMD01_preprocBOLD_uw_st0_s0_hpf100_filtered_func_data_denoised_s4_longt_mni4" # where the ICs reside ; ommit suffix '.gica'
DUALREG_IC_FILENAMES="melodic_IC.nii.gz"                    # 4D file with the IC of interest; it is to be found in the DUALREG_INPUT_ICA_DIRNAMES directories
DUALREG_INPUT_BOLD_FILES=""                                 # optional (if left empty, input files are derived elsewhere)
DUALREG_USE_MOVPARS_HPF="dummy"                             # cutoff period (s) for high-pass filtering motion parameters ; enter "none", "" or "dummy" if motion parameters should not be used, enter "Inf" if they should be used w/o hp-filtering (dr_stage2)
DUALREG_OUTDIR_PREFIX="dr"                                  # output directory pre-fix (dir-name is composed as: ${DUALREG_OUTDIR_PREFIX}_${DUALREG_INPUT_ICA_DIRNAMES}_${DUALREG_IC_FILENAMES})
DUALREG_NPERM=5000                                          # number of permutations
DUALREG_DELETE_PREV_RUNS=1                                  # delete previous runs?

# FSLNETS
FSLNETS_DREGDIRS="dreg_templates_melodicIC dreg_templates_melodicIC2"
FSLNETS_OUTIDR_PREFIX="fslnets"                             # output directory: ${FSLNETS_OUTIDR_PREFIX}_${FSLNETS_DREGDIRS}
FSLNETS_NPERM=5000
FSLNETS_GOODCOMPONENTS="[1 2 3 4 5 6 7 8 9 10]"
FSLNETS_T_THRESHOLDS="0:2:8"

# ----------------------------------------------------------------------

# misc.
BETLOWB_INFO="0.30"             # default bet values for b0 images
BETMAGN_INFO="0.50"             # default bet values for fieldmap magnitude images
BETSTRUC0_INFO="0.30 na na na"  # default bet values for t1 structurals (CoG na) - inital skullstrip (SSM)
BETSTRUC1_INFO="0.10 na na na"  # default bet values for t1 structurals (CoG na) - final skullstrip (SSM)
DWIUNWARP_INFO="+y"             # default direction values for unwarping DWIs (default: -y)
BOLDUNWARP_INFO="+y"            # default direction values for unwarping BOLDs (default: -y)
CHECK_INFOFILES=1               # check presence of info-files at startup and create default files if necessary
CHECK_CONSISTENCY_DIFFS=1       # checks number of bvals/bvecs entries at startup
RANDOMISE_PARALLEL=1            # use randomise_parallel for clusters
DELAYINSECS=150
